### ISSUE TITLE
Consideration for polygons

### ISSUE THREAD

**Issue by seasmith** [jjchern/gglorenz#2]
I would like to create a Lorenz curve as a polygon in the style of this chart from [Wikipedia](https://upload.wikimedia.org/wikipedia/commons/5/57/Lorenz_curve_of_Denmark%2C_Hungary%2C_and_Namibia.png):

![image](https://user-images.githubusercontent.com/16291809/70871246-a133bd00-1f62-11ea-825a-e0d95976ed58.png)

However, setting `geom = "polygon"`  only creates a polygon from the Lorenz curve to the abline (instead of the Lorenz curve to the axis).  Any ideas how to make this happen?

```r
library(tidyverse)
library(gglorenz)

ggplot(billionaires, aes(TNW)) +
    stat_lorenz(geom = "polygon")
```

![image](https://user-images.githubusercontent.com/16291809/70871287-4fd7fd80-1f63-11ea-8880-fd224f58714d.png)

Also, is there a method to control drawing order (using `factor()`)?  I'd like for the `"Real Estate"` group to draw on top of the `"Technology"` group.

```r
billionaires %>%
    filter(Industry %in% c("Technology", "Real Estate")) %>%
    ggplot(aes(x = TNW, fill = Industry)) +
    stat_lorenz(geom = "polygon", alpha = 0.5) +
    coord_fixed() +
    theme_minimal() +
    hrbrthemes::scale_x_percent() +
    hrbrthemes::scale_y_percent() +
    hrbrthemes::theme_ipsum() +
    labs(x = "Cumulative Percentage of Billionaires",
         y = "Cumulative Percentage of Total Net Worth",
         title = "Real Estate is a Relatively Equal Field",
         caption = "Source: https://www.bloomberg.com/billionaires/ (accessed February 8, 2018)")
```

![image](https://user-images.githubusercontent.com/16291809/70871273-0daebc00-1f63-11ea-8a9f-9ec51f288ce6.png)

**Comment by jjchern** [comment]
Thanks for the issue. 

You can use `geom = "area"` instead of `geom = "polygon"`:

```R
billionaires %>%
    filter(Industry %in% c("Technology", "Real Estate")) %>%
    ggplot(aes(x = TNW, fill = Industry)) +
    stat_lorenz(geom = "area", alpha = 0.65) +
    geom_abline(linetype = "dashed") +
    coord_fixed() +
    hrbrthemes::scale_x_percent() +
    hrbrthemes::scale_y_percent() +
    hrbrthemes::theme_ipsum() +
    labs(x = "Cumulative Quartiles",
         y = "Cumulative Percentage of Total Net Worth")
```

![image](https://user-images.githubusercontent.com/11262574/71136598-5a98c980-21d3-11ea-9300-de2950a36355.png)

You could add another row of data to produce the perfect equality portion:

```R
billionaires %>%
    filter(Industry %in% c("Technology", "Real Estate")) %>% 
    add_row(Industry = "Perfect Equality", TNW = 1) %>% 
    ggplot(aes(x = TNW, fill = Industry)) +
    stat_lorenz(geom = "area", alpha = 0.65) +
    coord_fixed() +
    hrbrthemes::scale_x_percent() +
    hrbrthemes::scale_y_percent() +
    hrbrthemes::theme_ipsum() +
    theme(legend.title = element_blank(),
          legend.position = "bottom") +
    labs(x = "Cumulative Quartiles",
         y = "Cumulative Percentage of Total Net Worth")
```

![image](https://user-images.githubusercontent.com/11262574/71136724-b2373500-21d3-11ea-957a-5952eaa277d0.png)

As for the drawing order, yes, you can use `factor()` or `forecast::as_factor()`:

```R
billionaires %>%
    filter(Industry %in% c("Technology", "Real Estate")) %>%
    mutate(Industry = factor(Industry, levels = c("Technology", "Real Estate"))) %>% 
    # Or use forcats::as_factor()
    # mutate(Industry = forcats::as_factor(Industry)) %>% 
    ggplot(aes(x = TNW, fill = Industry)) +
    stat_lorenz(geom = "polygon", alpha = 0.5) +
    coord_fixed() +
    theme_minimal()
```

![image](https://user-images.githubusercontent.com/11262574/71137082-f0812400-21d4-11ea-8b2e-8feeaef19b8d.png)

**Comment by seasmith** [comment]
Thanks, that takes care of it.
